### PR TITLE
Creates Continous Integration Configuration for CircleCI

### PR DESCRIPTION
**Pull request by Lennox-of-Shippo**

### CODE REVIEW

**Comment by assislucas** [comment]
Hey Lennox could you fix or remove the bad tests so we can see the full CI flow?

**Comment by Lennox-of-Shippo** [comment]
I will do that and let you know when its ready

**Comment by Lennox-of-Shippo** [comment]
Deploy to nuget is working.
Ready for another review.

**Review by assislucas — COMMENTED** [review]
What's `--recv-keys 3FA7E0328081BFF6A14DA29AA6` ? Is this sensitive information?

**Review by assislucas — COMMENTED** [review]
Did you make the GitHub version push work?

**Comment by Lennox-of-Shippo** [comment]
https://www.mono-project.com/download/stable/#download-lin

The keys are found here so likely public.

Github worked on ssh. I could edit the config to make it run a deploy job again.

**Comment by assislucas** [comment]
@Lennox-of-Shippo Please do another full deploy then to confirm everything works and then I can approve

**Review by assislucas — APPROVED** [review]
Looks good thanks!

**Pull request merged**
